# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# H0 X
# H0 X   libAtoms+QUIP: atomistic simulation library
# H0 X
# H0 X   Portions of this code were written by
# H0 X     Albert Bartok-Partay, Silvia Cereda, Gabor Csanyi, James Kermode,
# H0 X     Ivan Solt, Wojciech Szlachta, Csilla Varnai, Steven Winfield.
# H0 X
# H0 X   Copyright 2006-2010.
# H0 X
# H0 X   These portions of the source code are released under the GNU General
# H0 X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# H0 X
# H0 X   If you would like to license the source code under different terms,
# H0 X   please contact Gabor Csanyi, gabor@csanyi.net
# H0 X
# H0 X   Portions of this code were written by Noam Bernstein as part of
# H0 X   his employment for the U.S. Government, and are not subject
# H0 X   to copyright in the USA.
# H0 X
# H0 X
# H0 X   When using this software, please cite the following reference:
# H0 X
# H0 X   http://www.libatoms.org
# H0 X
# H0 X  Additional contributions by
# H0 X    Alessio Comisso, Chiara Gattinoni, and Gianpietro Moras
# H0 X
# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

${BUILDDIR}/Makefile.inc: ${BUILDDIR}
ifneq (${shell [ -f ${BUILDDIR}/Makefile.inc ] && echo 1 || echo 0},1)
	@echo
	@echo "In the following, hit enter to accept the defaults."
ifndef MATH_LINKOPTS
	@echo
	@echo "Please enter the linking options for LAPACK and BLAS libraries:"
	@echo "   Default: ${DEFAULT_MATH_LINKOPTS}"
	@read MATH_LINKOPTS && if [[ $$MATH_LINKOPTS == "" ]] ; then \
	  echo "MATH_LINKOPTS=${DEFAULT_MATH_LINKOPTS}" >> ${BUILDDIR}/Makefile.inc ; \
	  else echo "MATH_LINKOPTS=$$MATH_LINKOPTS" >> ${BUILDDIR}/Makefile.inc ; fi
endif
ifndef FOX_LIBDIR
	@echo
	@echo "Please enter directory where FoX libraries are kept:"
	@echo "   Default: use included version ${FOX}"
	@read FOX_LIBDIR && if [[ $$FOX_LIBDIR ]] ; then \
	  echo "FOX_LIBDIR=$$FOX_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
	  echo ; \
	  echo "Please enter directory where FoX include files are kept:" ; \
	  read FOX_INCDIR && echo "FOX_INCDIR=$$FOX_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
	  echo "HAVE_EXTERNAL_FOX=1" >> ${BUILDDIR}/Makefile.inc ; \
	 else echo "FOX_LIBDIR=$${PWD}/FoX-4.0.3/objs.${QUIP_ARCH}/lib" >> ${BUILDDIR}/Makefile.inc ; \
	  echo "FOX_INCDIR=$${PWD}/FoX-4.0.3/objs.${QUIP_ARCH}/finclude" >> ${BUILDDIR}/Makefile.inc ; \
	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
endif
ifndef NETCDF_LIBDIR
	@echo
	@echo "Please enter directory where NetCDF libraries are kept:"
	@echo "   Default: no NetCDF present"
	@read NETCDF_LIBDIR && if [[ $$NETCDF_LIBDIR ]] ; then \
	  echo "NETCDF_LIBDIR=$$NETCDF_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
	  echo ; \
	  echo "Please enter directory where NetCDF include files are kept:" ; \
	  read NETCDF_INCDIR && echo "NETCDF_INCDIR=$$NETCDF_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
	  echo "HAVE_NETCDF=1" >> ${BUILDDIR}/Makefile.inc ; \
	  if nm $$NETCDF_LIBDIR/libnetcdf.a | grep -q deflate; then \
	   echo "NetCDF version 4 found." ; \
	   echo "NETCDF4=1" >> ${BUILDDIR}/Makefile.inc ; \
	  else echo "NetCDF older than version 4 found." ; \
	   echo "NETCDF4=0" >> ${BUILDDIR}/Makefile.inc; fi \
	 else echo "HAVE_NETCDF=0" >> ${BUILDDIR}/Makefile.inc ; fi
endif
ifndef LARSPOT_LIBDIR
	@echo
	@echo "Please enter directory where the Lars Potential libraries are kept:"
	@echo "   Default: no Lars potential present"
	@read LARSPOT_LIBDIR && if [[ $$LARSPOT_LIBDIR ]] ; then \
	  echo "LARSPOT_LIBDIR=$$LARSPOT_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
	  echo ; \
	  echo "Please enter directory where Lars Potential include files are kept:" ; \
	  read LARSPOT_INCDIR && echo "LARSPOT_INCDIR=$$LARSPOT_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
	  echo "HAVE_LARSPOT=1" >> ${BUILDDIR}/Makefile.inc ; \
	 else echo "HAVE_LARSPOT=0" >> ${BUILDDIR}/Makefile.inc ; fi
endif
ifndef ASAP_LIBDIR
	@echo
	@echo "Please enter directory where the ASAP Potential libraries are kept:"
	@echo "   Default: no ASAP potential present"
	@read ASAP_LIBDIR && if [[ $$ASAP_LIBDIR ]] ; then \
	  echo "ASAP_LIBDIR=$$ASAP_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
	  echo "HAVE_ASAP=1" >> ${BUILDDIR}/Makefile.inc ; \
	 else echo "HAVE_ASAP=0" >> ${BUILDDIR}/Makefile.inc ; fi
endif
ifndef EXTRA_LINKOPTS
	@echo
	@echo "Please enter any other extra linking options:"
	@echo "   Default: none"
	@read EXTRA_LINKOPTS && echo "EXTRA_LINKOPTS=$$EXTRA_LINKOPTS" >> ${BUILDDIR}/Makefile.inc
endif
	@echo "HAVE_LOTF=1" >> ${BUILDDIR}/Makefile.inc
	@echo "HAVE_GP=0" >> ${BUILDDIR}/Makefile.inc
	@echo "HAVE_QP=0" >> ${BUILDDIR}/Makefile.inc
	@echo "GP_PREDICT_QP=0" >> ${BUILDDIR}/Makefile.inc
	@echo "OPTIM=${DEFAULT_OPTIM}" >> ${BUILDDIR}/Makefile.inc
	@echo "DEBUG=${DEFAULT_DEBUG}" >> ${BUILDDIR}/Makefile.inc
endif
