# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# H0 X
# H0 X   libAtoms+QUIP: atomistic simulation library
# H0 X
# H0 X   Portions of this code were written by
# H0 X     Albert Bartok-Partay, Silvia Cereda, Gabor Csanyi, James Kermode,
# H0 X     Ivan Solt, Wojciech Szlachta, Csilla Varnai, Steven Winfield.
# H0 X
# H0 X   Copyright 2006-2010.
# H0 X
# H0 X   These portions of the source code are released under the GNU General
# H0 X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# H0 X
# H0 X   If you would like to license the source code under different terms,
# H0 X   please contact Gabor Csanyi, gabor@csanyi.net
# H0 X
# H0 X   Portions of this code were written by Noam Bernstein as part of
# H0 X   his employment for the U.S. Government, and are not subject
# H0 X   to copyright in the USA.
# H0 X
# H0 X
# H0 X   When using this software, please cite the following reference:
# H0 X
# H0 X   http://www.libatoms.org
# H0 X
# H0 X  Additional contributions by
# H0 X    Alessio Comisso, Chiara Gattinoni, and Gianpietro Moras
# H0 X
# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

.SUFFIXES: .c .h .f .f95 .f90 .fpp

FOX_LIBS = -lFoX_sax -lFoX_wxml -lFoX_utils -lFoX_common -lFoX_fsys
FX_LIB = -lfx
NETCDF_LIBS =  -lnetcdf
NETCDF4_LIBS = -lnetcdf -lhdf5_hl -lhdf5 $(NETCDF4_EXTRA_LIBS)
NETCDF4_CURL_LIBS = -lcurl
MDCORE_LIBS = -lmdcore
GIT_VERSION := -D'GIT_VERSION="$(shell ${QUIP_ROOT}/utility_scripts/gitversion -n ..)"'
GAP_VERSION := -D'GAP_VERSION=$(shell ${QUIP_ROOT}/utility_scripts/gapversion.sh -n ..)'

ifndef AR
	AR = ar
endif
RANLIB = ranlib
NM = nm --print-file-name --extern-only --defined-only --no-sort --portability

ifeq (${COPTIM},)
  COPTIM=${OPTIM}
endif
ifeq (${CDEBUG},)
  CDEBUG=${DEBUG}
endif

DEFINES += ${GIT_VERSION} ${GAP_VERSION} -D'QUIP_ARCH="${QUIP_ARCH}"' -D'SIZEOF_FORTRAN_T=${SIZEOF_FORTRAN_T}'
F95FLAGS += ${INCLUDES} ${OPTIM} ${DEBUG} ${DEFINES} ${CUSTOM_F95FLAGS}
F77FLAGS += ${INCLUDES} ${OPTIM} ${DEBUG} ${DEFINES} ${CUSTOM_F77FLAGS}
CPLUSPLUSFLAGS += ${INCLUDES} ${COPTIM} ${CDEBUG} ${DEFINES} ${CUSTOM_CPLUSPLUSFLAGS}
CFLAGS += ${INCLUDES} ${COPTIM} ${CDEBUG} ${DEFINES} ${CUSTOM_CFLAGS}

SYSLIBS += -L${FOX_LIBDIR} ${FOX_LIBS} 
INCLUDES += -I${QUIP_ROOT}/libAtoms -I${FOX_INCDIR}

ifeq (${HAVE_NETCDF},1)
  SYSLIBS += $(addprefix -L,${NETCDF_LIBDIR})
  INCLUDES += $(addprefix -I,${NETCDF_INCDIR})
  ifeq (${NETCDF4}, 1)
    DEFINES += -DHAVE_NETCDF -DNETCDF4
    SYSLIBS +=  ${NETCDF4_LIBS}
    ifeq (${NETCDF4_CURL}, 1)
      SYSLIBS +=  ${NETCDF4_CURL_LIBS}
    endif
  else
    DEFINES  += -DHAVE_NETCDF
    SYSLIBS +=  ${NETCDF_LIBS}
  endif
endif
ifeq (${HAVE_MDCORE},1)
  SYSLIBS += -L${MDCORE_LIBDIR} ${MDCORE_LIBS}
  INCLUDES += -I${MDCORE_INCDIR}
  DEFINES  += -DHAVE_MDCORE
endif
ifeq (${HAVE_ASAP},1)
  SYSLIBS += -L${ASAP_LIBDIR} -lasap
  INCLUDES += -I${ASAP_LIBDIR}
  DEFINES += -DHAVE_ASAP
endif
ifeq (${HAVE_KIM},1)
  SYSLIBS += -L${KIM_DIR}/kim-api-v1 -lkim-api-v1  -lstdc++
  INCLUDES += -I${KIM_DIR}/kim-api-v1/include 
  DEFINES += -DHAVE_KIM
  ifeq (${KIM_NO_AUTOGENERATE_TEST_KIM},1)
    DEFINES += -DKIM_NO_AUTOGENERATE_TEST_KIM
  endif
endif
ifeq (${HAVE_FX},1)
  DEFINES += -DHAVE_FX
  SYSLIBS += ${FX_LIB}
endif
ifeq (${HAVE_GAP_FILLER},1)
  DEFINES += -DHAVE_GAP_FILLER
  HAVE_GAP = 1
endif
ifeq (${HAVE_GAP},1)
  DEFINES += -DHAVE_GAP
  GP_LIB += -lgap_predict
  GP_LIBFILE += libgap_predict.a
endif
ifeq (${HAVE_TB},1)
  DEFINES += -DHAVE_TB
endif
ifeq (${HAVE_QP_TEACH},1)
  DEFINES += -DHAVE_QP -DHAVE_QP_TEACH
endif
ifeq (${HAVE_QP_PREDICT},1)
  DEFINES += -DHAVE_QP -DHAVE_QP_PREDICT
endif
ifeq (${HAVE_QR},1)
  DEFINES += -DHAVE_QR
endif
ifeq (${HAVE_LOTF},1)
  DEFINES += -DHAVE_LOTF
endif
ifeq (${HAVE_CP2K},1)
  DEFINES += -DHAVE_CP2K
endif
ifeq (${HAVE_ONIOM},1)
  DEFINES += -DHAVE_ONIOM
endif
ifeq (${HAVE_LOCAL_E_MIX},1)
  DEFINES += -DHAVE_LOCAL_E_MIX
endif
ifeq (${HAVE_CGAL},1)
  DEFINES += -DHAVE_CGAL
  CUSTOM_CPLUSPLUSFLAGS += -frounding-math -DCGAL_FPU_HAS_EXCESS_PRECISION
  INCLUDES += $(addprefix -I,${CGAL_INCDIR})
  SYSLIBS += $(addprefix -L,${CGAL_LIBDIR})
  SYSLIBS += -lCGAL -lgmpxx -lmpfr -lgmp -lboost_thread-mt -lstdc++ #/usr/lib/libstdc++.6.dylib
endif
ifeq (${HAVE_THIRDPARTY},1)
  DEFINES += -DHAVE_THIRDPARTY
endif

SYSLIBS += ${MATH_LINKOPTS} ${EXTRA_LINKOPTS}

LINKOPTS += ${OPTIM} ${DEBUG} ${SYSLIBS} ${CUSTOM_LINKOPTS}

.f.o:
	${F77}  ${F77FLAGS} -c $< -o $@

.c.o:	
	${CPLUSPLUS} ${CPLUSPLUSFLAGS} -c $<  -o $@

.cpp.o:	
	${CPLUSPLUS} ${CPLUSPLUSFLAGS} -c $<  -o $@

.f95.o:
	${F95}  ${F95FLAGS} -c ${F95_PRE_FILENAME_FLAG} $< -o $@

.f90.o:
	${F95}  ${F95FLAGS} -c ${F95_PRE_FILENAME_FLAG} $< -o $@

FPP_PRE_TARGET_STRING ?= >

.f95.fpp:
	${FPP}  ${F95FLAGS} ${F95_PRE_FILENAME_FLAG} $< ${FPP_PRE_TARGET_STRING} $@

%.o : %.mod

-include Makefiles/Makefile.rules.${QUIP_ARCH}
