# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# H0 X
# H0 X   libAtoms+QUIP: atomistic simulation library
# H0 X
# H0 X   Portions of this code were written by
# H0 X     Albert Bartok-Partay, Silvia Cereda, Gabor Csanyi, James Kermode,
# H0 X     Ivan Solt, Wojciech Szlachta, Csilla Varnai, Steven Winfield.
# H0 X
# H0 X   Copyright 2006-2010.
# H0 X
# H0 X   These portions of the source code are released under the GNU General
# H0 X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# H0 X
# H0 X   If you would like to license the source code under different terms,
# H0 X   please contact Gabor Csanyi, gabor@csanyi.net
# H0 X
# H0 X   Portions of this code were written by Noam Bernstein as part of
# H0 X   his employment for the U.S. Government, and are not subject
# H0 X   to copyright in the USA.
# H0 X
# H0 X
# H0 X   When using this software, please cite the following reference:
# H0 X
# H0 X   http://www.libatoms.org
# H0 X
# H0 X  Additional contributions by
# H0 X    Alessio Comisso, Chiara Gattinoni, and Gianpietro Moras
# H0 X
# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

.SUFFIXES: .c .h .f .f95 .fpp

FOX_LIBS = -lFoX_sax -lFoX_wxml -lFoX_utils -lFoX_common -lFoX_fsys
NETCDF_LIBS =  -lnetcdf
NETCDF4_LIBS = -lnetcdf -lhdf5_hl -lhdf5 $(NETCDF4_EXTRA_LIBS)
NETCDF4_CURL_LIBS = -lcurl
LARSPOT_LIBS = -lmdcore
SVN_VERSION := -D'SVN_VERSION="$(shell svnversion -n ..)"'

ifndef AR
	AR = ar
endif
RANLIB = ranlib
NM = nm --print-file-name --extern-only --defined-only --no-sort --portability

ifeq (${COPTIM},)
  COPTIM=${OPTIM}
endif
ifeq (${CDEBUG},)
  CDEBUG=${DEBUG}
endif

DEFINES = ${SVN_VERSION}
F95FLAGS = ${INCLUDES} ${OPTIM} ${DEBUG} ${DEFINES} 
F77FLAGS = ${INCLUDES} ${OPTIM} ${DEBUG} ${DEFINES} 
CPLUSPLUSFLAGS = ${INCLUDES} ${COPTIM} ${CDEBUG} ${DEFINES} 
CFLAGS = ${INCLUDES} ${COPTIM} ${CDEBUG} ${DEFINES} 

SYSLIBS = -L${FOX_LIBDIR} ${FOX_LIBS}
INCLUDES = -I${QUIP_ROOT}/libAtoms -I${FOX_INCDIR}

ifeq (${HAVE_NETCDF},1)
  SYSLIBS += $(addprefix -L,${NETCDF_LIBDIR})
  INCLUDES += $(addprefix -I,${NETCDF_INCDIR})
  ifeq (${NETCDF4}, 1)
    DEFINES += -DHAVE_NETCDF -DNETCDF4
    SYSLIBS +=  ${NETCDF4_LIBS}
    ifeq (${NETCDF4_CURL}, 1)
      SYSLIBS +=  ${NETCDF4_CURL_LIBS}
    endif
  else
    DEFINES  += -DHAVE_NETCDF
    SYSLIBS +=  ${NETCDF_LIBS}
  endif
endif
ifeq (${HAVE_LARSPOT},1)
  SYSLIBS += -L${LARSPOT_LIBDIR} ${LARSPOT_LIBS}
  INCLUDES += -I${LARSPOT_INCDIR}
  DEFINES  += -DHAVE_MDCORE
endif
ifeq (${HAVE_ASAP},1)
  SYSLIBS += -L${ASAP_LIBDIR} -lasap
  INCLUDES += -I${ASAP_LIBDIR}
  DEFINES += -DHAVE_ASAP
endif
ifeq (${HAVE_GP},1)
  DEFINES += -DHAVE_GP
  GP_LIB=-lgp
  GP_LIBFILE=libgp.a
endif
ifeq (${HAVE_TB},1)
  DEFINES += -DHAVE_TB
endif
ifeq (${HAVE_QP},1)
  DEFINES += -DHAVE_QP
endif
ifeq (${GP_PREDICT_QP},1)
  DEFINES += -DGP_PREDICT_QP
endif
ifeq (${HAVE_QR},1)
  DEFINES += -DHAVE_QR
endif
ifeq (${HAVE_LOTF},1)
  DEFINES += -DHAVE_LOTF
endif
ifeq (${HAVE_ONIOM},1)
  DEFINES += -DHAVE_ONIOM
endif
ifeq (${HAVE_LOCAL_E_MIX},1)
  DEFINES += -DHAVE_LOCAL_E_MIX
endif
SYSLIBS += ${MATH_LINKOPTS} ${EXTRA_LINKOPTS}

LINKOPTS = ${OPTIM} ${DEBUG} ${SYSLIBS}

.f.o:
	${F77}  ${F77FLAGS} -c $< -o $@

.f95.o:
	${F95}  ${F95FLAGS} -c $< -o $@

.c.o:	
	${CPLUSPLUS} ${CPLUSPLUSFLAGS} -c $<  -o $@
