#!/usr/bin/env python
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

from pyatoms import *
import sys

if (len(sys.argv)) != 4:
   print 'Usage: cpembed <source of embed mask.xyz> <source of positions.xyz> <dest.xyz>'
   sys.exit(1)

at1 = Atoms(sys.argv[1])
at2 = Atoms(sys.argv[2])

if at1.n != at2.n:
   print 'Error: at1.n (%d) != at2.n (%d)' % (at1.n, at2.n)
   sys.exit(1)

at2.aux[:,0] = at1.aux[:,0]


outf = open(sys.argv[3], 'w')
at2.write(outf)
outf.close()
