#!/usr/bin/env python
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

import sys
from pyatoms import *
from numpy import *

at = Atoms(sys.argv[1])

def sphere(c,r):
    return (norm(at.pos - c)) < r

def cracktip(r):
    return sphere(array((at.params['CrackPos'],0.0,0.0)),r)

condition = eval(sys.argv[2])
nz = condition.nonzero()[0]

print '%d/%d atoms' % (len(nz), at.n)

filter = open(sys.argv[1]+'.filter','w')
filter.write('\n'.join(map(str, nz)))
filter.write('\n')
filter.close()
