#!/usr/bin/env python
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

import sys
from pyatoms import *
from pyatoms.sio2utils import *

if __name__ == '__main__':
   if len(sys.argv[1:]) not in (3,4):
      print 'Usage: poscel2xyz <pos.in> <cel.in> <out.xyz> [dt]'
      sys.exit(0)

   a1, a2 = read_pos_cel(sys.argv[1], sys.argv[2])

   f = open(sys.argv[3], 'w')

   a1.write_xyz(f)
   a2.write_xyz(f)

   if len(sys.argv[1:]) == 4:
      dt = float(sys.argv[2])
      a3 = a2.copy()
      a3.add_property('velo', (a2.pos - a1.pos)/(dt*AU_FS))
      a3.write_xyz(f)

   f.close()


   
