#!/usr/bin/env python
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

from pyatoms import *
import sys

if len(sys.argv) != 4:
   print 'Usage: strain <in file> <out file> <new strain>'
   sys.exit(1)

at = Atoms(sys.argv[1])

old_strain = at.params['Strain']
new_strain = float(sys.argv[3])
alpha = (new_strain - old_strain)/(1.0 + old_strain)

print 'Current strain : ', old_strain
print 'Output  strain : ', new_strain
print 'Scaling factor : ', alpha

# Scale y coordinates by factor of (1 + alpha)
at.pos[:,1] = at.pos[:,1]*(1.0 + alpha)

at.params['Strain'] = new_strain

outf = open(sys.argv[2], 'w')
at.write(outf)
outf.close()

