#!/usr/bin/env python
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

import sys
from pyatoms import *
from pyatoms.sio2utils import *

if __name__ == '__main__':
   if len(sys.argv[1:]) not in (1,2):
      print 'Usage: xyz2poscel <frame1.xyz> [<frame2.xyz>]'

   if len(sys.argv[1:]) == 2:
      f1 = Atoms(sys.argv[1])
      f2 = Atoms(sys.argv[2])
   else:
      f = open(sys.argv[1])
      f1 = Atoms()
      f1.read_xyz(f)
      f2 = Atoms()
      f2.read_xyz(f)
      f.close()

   write_pos_cel(f1, f2)
