#!/usr/bin/env python

import sys
from pyatoms import *
from pyatoms.sio2utils import *

if __name__ == '__main__':
   if len(sys.argv[1:]) not in (1,2):
      print 'Usage: xyz2poscel <frame1.xyz> [<frame2.xyz>]'

   if len(sys.argv[1:]) == 2:
      f1 = Atoms(sys.argv[1])
      f2 = Atoms(sys.argv[2])
   else:
      f = open(sys.argv[1])
      f1 = Atoms()
      f1.read_xyz(f)
      f2 = Atoms()
      f2.read_xyz()
      f.close()

   write_pos_cel(f1, f2)
