#!/usr/bin/env python

import sys, os

# obtain list of users with access to our repo
group = os.popen('ssh cvs.tcm.phy.cam.ac.uk group -l jrk33').read()
users = group.split(':')[1].split()
users = set(users) # remove duplicates

# download cvs-users mailing list from TCM
cvs_users = os.popen('ssh jrk33@pc41.tcm.phy.cam.ac.uk grep "^#%" -A1 ~lists/cvs-users').read().split('\n')

# Extract usernames and email addresses from cvs-users mailing list
emails = {}
for user, email in zip(cvs_users[::3], cvs_users[1::3]):
   user = user[2:].strip()
   email = email.strip()
   if user in users:
      emails[user] = email

# Fill in missing users with @tcm email address
for user in users:
   if user not in emails:
      emails[user] = '%s@tcm.phy.cam.ac.uk' % user

# Print two columns: user email
for user, email in emails.iteritems():
   print '%-15s%s' % (user, email)
   
