#!/bin/bash

# Location of libAtoms relative to QUIP - needed to find f90doc 
libAtoms_dir=../libAtoms

# Remove old documentation
rm -rf doctmp
mkdir doctmp
cd doctmp

# Make a copy of all input source files with function and subroutine
# names at the end of each subprogram, so that f90doc doesn't get
# confused
for f in $@; do
    echo $f
    perl -e '
while(<>) {
    if (/^(double precision\s+)?\s*(recursive\s+)?(subroutine|function)\s+(\w*)/) {
	$last_subrt = $4;
	print $_;
    }
    elsif (/^\s*end\s+(subroutine|function)\s*$/) {
	chomp($_);
	print $_." ".$last_subrt."\n";
    }
    else { print $_; }
}' ../$f > `basename $f`
done

# Now feed it to f90doc from libAtoms CVS module
../$libAtoms_dir/f90doc -t 'QUIP Reference Manual' \
    -a "Noam Bernstein, G\\'abor Cs\\'anyi, James Kermode, Silvia Cereda" -l *.f95 > quip.tex

# Copy in the introduction
cp ../intro.tex .

# LaTeX it
latex quip.tex
latex quip.tex
makeindex general
latex quip.tex

# Make postscript
dvips quip.dvi -o quip.ps

# And PDF
dvipdfm quip.dvi

# Uncomment this line if you have latex2html and want HTML docs
#latex2html quip.tex

# Copy output files out of 'doctmp'
cp quip.ps ..
cp quip.pdf ..