# HQ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HQ X
# H0 X   libAtoms+QUIP: atomistic simulation library
# HQ X
# HQ X   Portions of this code were written by
# HQ X     Tamas K. Stenczel
# HQ X
# HQ X   Copyright 2021
# HQ X
# HQ X
# HQ X   Edited by Vlad Carare and Lars Schaaf - working as of 07.04.2022
# HQ X
# HQ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# ACRHER2 computer cluster, United Kingdom
#
# recommended modules to use with this:
# - GNU compilers version 9, python and FFTW
# - obtain these with the following on Archer2
#
# module switch PrgEnv-cray PrgEnv-gnu
# module load PrgEnv-gnu
# module load gcc/9.3.0
# module load cray-fftw


# declarations

include arch/Makefile.archer2
# OpenMP and compiler wrappers already defined in the archer2 makefile

# MPI
DEFINES += -D_MPI

# NOTE: Make sure to erase the defaults ("-llapack -lblas") when being prompted for "linking options for LAPACK and BLAS libraries". 
#       On Archer2 the compiler wrappers (cc CC ftn) will link to the libsci library, which includes LAPACK and BLAS.
