# declarations

F77 = ifort
F90 = ifort
F95 = ifort
CC = icc
CPLUSPLUS = icpc -Kc++
LINKER = ifort

SAMPLE_DEBUG = -g -traceback -check bounds -DDUMP_CORE_ON_ABORT 
DEBUG = -g -traceback -DDUMP_CORE_ON_ABORT 
OPTIM = -O3 -vec-report0 -unroll -xP -p
CDEBUG = -g -DDUMP_CORE_ON_ABORT
COPTIM = -O3

DEFINES = -DGETARG_F2003 -DFORTRAN_UNDERSCORE -DDARWIN
F95FLAGS += -fpp -free 
F77FLAGS += -fixed

DEFAULT_MATH_LINKOPTS = -framework Accelerate

AR_ADD = src

# rules

F95_PRE_FILENAME_FLAG = -Tf
