Potentials_F90_sources = [
  'AdjustablePotential.F90',
  'ApproxFermi.F90',
  'CallbackPot.F90',
  'ElectrostaticEmbed.F90',
  'Ewald.F90',
  'FilePot.F90',
  'Functions.F90',
  'IP.F90',
  'IPEwald.F90',
  'IPModel_ASAP.F90',
  'IPModel_BOP.F90',
  'IPModel_BornMayer.F90',
  'IPModel_Brenner.F90',
  'IPModel_Brenner_2002.F90',
  'IPModel_Brenner_Screened.F90',
  'IPModel_CH4.F90',
  'IPModel_ConfiningMonomer.F90',
  'IPModel_Coulomb.F90',
  'IPModel_Custom.F90',
  'IPModel_DispTS.F90',
  'IPModel_EAM_Ercolessi_Adams.F90',
  'IPModel_Einstein.F90',
  'IPModel_FB.F90',
  'IPModel_FC.F90',
  'IPModel_FC4.F90',
  'IPModel_FS.F90',
  'IPModel_FX.F90',
  'IPModel_GAP.F90',
  'IPModel_Glue.F90',
  'IPModel_HFdimer.F90',
  'IPModel_LJ.F90',
  'IPModel_LMTO_TBE.F90',
  'IPModel_LinearSOAP.F90',
  'IPModel_MBD.F90',
  'IPModel_MTP.F90',
  'IPModel_Morse.F90',
  'IPModel_Multipoles.F90',
  'IPModel_PartridgeSchwenke.F90',
  'IPModel_RS.F90',
  'IPModel_SCME.F90',
  'IPModel_SW.F90',
  'IPModel_SW_VP.F90',
  'IPModel_Si_MEAM.F90',
  'IPModel_Spring.F90',
  'IPModel_Sutton_Chen.F90',
  'IPModel_TS.F90',
  'IPModel_Template.F90',
  'IPModel_Tersoff.F90',
  'IPModel_Tether.F90',
  'IPModel_TTM_nF.F90',
  'IPModel_WaterDimer_Gillan.F90',
  'IPModel_WaterTrimer_Gillan.F90',
  'IPModel_ZBL.F90',
  'IPModel_vdW.F90',
  'Multipole_Interactions.F90',
  'Multipoles.F90',
  'Partridge_Schwenke_Dipole.F90',
  'Potential.F90',
  'Potential_Precon_Minim.F90',
  'Potential_simple.F90',
  'QC_QUIP_Wrapper.F90',
  'QUIP_Common.F90',
  'QUIP_module.F90',
  'RS_SparseMatrix.F90',
  'SocketPot.F90',
  'TB.F90',
  'TBMatrix.F90',
  'TBModel.F90',
  'TBModel_Bowler.F90',
  'TBModel_DFTB.F90',
  'TBModel_GSP.F90',
  'TBModel_NRL_TB.F90',
  'TBModel_NRL_TB_defs.F90',
  'TBSystem.F90',
  'TB_Common.F90',
  'TB_GreensFunctions.F90',
  'TB_Kpoints.F90',
  'TB_Mixing.F90',
  'Yukawa.F90',
  'quip_lammps_wrapper.F90',
  'quip_unified_wrapper.F90',

]

Potentials_F77_sources = [
  'ginted.F'
]

Potentials = library('Potentials',
  Potentials_F77_sources+Potentials_F90_sources,
  dependencies: [
    blas_dep,
    mpi_dep,
    ],
  link_with : [libAtoms,fox,GAP],
  link_args: openmp_link_args,
  )
