#!/bin/bash
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

function print_usage {
    echo "Extract parameters from the comment lines of an extended XYZ file"
    echo 
    echo "Usage: $0 param1 [param2]... < movie.xyz"
    exit
}

[[ $# -ge 1 ]] || print_usage

props=$@

grep 'Lattice=' | awk '
{
  split(props,ps);
  for (p in ps) {
    regex=ps[p] "=\"?([^\" ]*)";
    match($0,regex,a);
    printf "%f ",a[1]; 
  }
  printf "\n";
}' props="$props" 