#!/usr/bin/env python
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

import sys
from math import *

xyz1 = open(sys.argv[1])
xyz2 = open(sys.argv[2])

# Get number of atoms
n1 = int(xyz1.readline())
n2 = int(xyz2.readline())

if n1 != n2:
   print 1000.0 # a big number
   sys.exit(0)

# Throw away comment
xyz1.readline()
xyz2.readline()

total = 0.0
maxdiff = 0.0
for n in range(n1):
   line1 = xyz1.readline().split()
   line2 = xyz2.readline().split()

   x1 = map(float,line1[1:4])
   x2 = map(float,line2[1:4])
   for i in range(3):
      total = total + (x1[i] - x2[i])**2
      if abs(x1[i]-x2[i]) > maxdiff:
         maxdiff = abs(x1[i]-x2[i])
   
# Print RMS difference
print sqrt(total / n1)

# and max difference
print maxdiff
