#!/bin/awk -f
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# HP X
# HP X   pyatoms: atomistic simulations tools
# HP X
# HP X   Copyright James Kermode 2010
# HP X
# HP X   These portions of the source code are released under the GNU General
# HP X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# HP X
# HP X   If you would like to license the source code under different terms,
# HP X   please contact James Kermode, james.kermode@gmail.com
# HP X
# HP X   When using this software, please cite the following reference:
# HP X
# HP X   http://www.jrkermode.co.uk/PyAtoms
# HP X
# HP XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BEGIN {
  split(ARGV[1],a,"."); 
  clrbase=a[1]
  frame=0;

  # Column to colour by
  col=5;

  # Mapping of $col values to RGB colours
  colour[0]="0.85 0.85 0.25";
  colour[1]="1.00 0.00 0.00";
  colour[3]="1.00 0.00 0.00";
}

{
  clrfile=clrbase sprintf("%05d",frame) ".clr";

  natoms=$1;
  printf "Frame "frame": " natoms" atoms              \r";

  getline comment;

  for (i=0; i<natoms; i++) {
    getline;
    
    printf "%s\n",colour[int($col)] >> clrfile;
  }     

  close(clrfile);
  frame=frame+1;
}

END {
  print "Done "frame" frames.                  "
}
