OPTIM = -O3 -ip -unroll
#OPTIM = 
#OPTIM =  -O0

#DEBUG = -pg -g -Wall
#DEBUG = -pg -Wall
#DEBUG = -Wall

#DEFS =  -DMEM_TRACE -DUTIL_MPI

CPLUSPLUS = icc -Kc++

CC = icc

F77 = ifc 
F77OPTS = -cpp

AROPTS=src

LINKER = ${F77}


UTILLIB = libutil-icc.a

MATHLIBS =   -lmkl_lapack -lmkl_p4 -lguide -lpthread  



