OPTIM = -O3 -ip -unroll
#OPTIM = 
#OPTIM =  -O0

#DEBUG = -pg -g -Wall
#DEBUG = -pg -Wall
#DEBUG = -Wall

#DEFS =   -DMEM_TRACE -DUTIL_MPI
DEFS =  -DUTIL_MPI 


CPLUSPLUS = icc -Kc++

CC = icc

F77 = ifc 
F77OPTS = -cpp

LINKER = ${F77}

AROPTS=src

UTILLIB=libutil-icc.a






