# declarations

F77 = mpif77
F90 = mpif90
F95 = mpif90
CC = mpicc
CPLUSPLUS = mpiCC

DEBUG = -g -traceback
OPTIM = -O3
FOPTIM = -O3 -ip

MPI_DEFS = -D_MPI -DMPI_1 -DSCALAPACK

ARCH_F95FLAGS =  -fpp -free ${FOPTIM} ${MPI_DEFS} ${DEBUG}
ARCH_F77FLAGS =  -fpp ${FOPTIM} ${MPI_DEFS} ${DEBUG}
ARCH_CCFLAGS =  -DFORTRAN_UNDERSCORE ${OPTIM} ${MPI_DEFS} ${DEBUG}
ARCH_CPLUSPLUSFLAGS =  -DFORTRAN_UNDERSCORE ${OPTIM} ${MPI_DEFS} ${DEBUG}
ARCH_LINKFLAGS =  ${FOPTIM} ${DEBUG}

MAKEDEP_ARGS = -lc -suffix .mod

AR_ADD = src

ARCH_LIBDIRS = ${ACML_LIBPATH} -L/share/apps/ScaLAPACK/current/ifort64/mpi1
ARCH_LAPACK_LIBS = -lscalapack -lblacsF77init -lblacs ${ACML_LIB}

ARCH_FOX_LIBDIR = -L${HOME}/src/work/FORTRAN_XML/FoX-4.0.3/objs_ifort64/lib
ARCH_FOX_INCLUDEDIR = -I${HOME}/src/work/FORTRAN_XML/FoX-4.0.3/objs_ifort64/finclude
ARCH_FOX_LIBS=-lFoX_sax -lFoX_wxml -lFoX_utils -lFoX_common -lFoX_fsys

LINKER = mpif90
ARCH_LIBS =

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${COMMON_F95FLAGS} ${ARCH_F95FLAGS} ${EXTRA_F95FLAGS} -c -Tf $<
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
