# declarations

F77 = ifort
F90 = ifort
F95 = ifort
CC = gcc
CPLUSPLUS = g++
LINKER = ifort

# -g slows down ifort immensely
SAMPLE_DEBUG = -g -traceback -DDUMP_CORE_ON_ABORT -check bounds
DEBUG = -DDUMP_CORE_ON_ABORT
OPTIM = -O3 -vec-report0 -fPIC -DPOTENTIAL_NO_DEFAULT_PRIVATE
CDEBUG = -g -DDUMP_CORE_ON_ABORT
COPTIM = -O3 -fPIC

DEFINES += -DGETARG_F2003 -D_OPENMP
F95FLAGS += -fpp -free -warn unused -openmp
F77FLAGS += -fpp -fixed -openmp
CFLAGS +=  -DFORTRAN_UNDERSCORE
CPLUSPLUSFLAGS +=  -DFORTRAN_UNDERSCORE 
LINKOPTS += -openmp

MAKEDEP_ARGS = -lc -suffix .mod
AR_ADD = src

QUIPPY_INSTALL_OPTS = --home=${HOME}
QUIPPY_FCOMPILER = intelem
QUIPPY_F90FLAGS = -fpp -free
QUIPPY_OPT = -O3 -vec-report0
QUIPPY_CPP = ifort -EP
# QUIPPY_NO_QUIP = 1
# QUIPPY_NO_TOOLS = 1
QUIPPY_NO_CRACK = 1

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${F95FLAGS} -c -Tf $< -o $@
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
