# declarations

F77 = mpif77 #ifort
F90 = mpif90 #ifort
F95 = mpif90 #ifort
CC = mpicc #icc
CPLUSPLUS = mpiCC #icpc -Kc++
LINKER = mpif90 #ifort

DEFAULT_DEBUG = -g -traceback -check bounds -DDUMP_CORE_ON_ABORT 
DEFAULT_OPTIM = -O3 -vec-report0 -unroll -xP -p 
CDEBUG = -g -DDUMP_CORE_ON_ABORT
COPTIM = -O3

F95FLAGS += -fpp -free -DGETARG_F2003 -warn unused -D_MPI -D
F77FLAGS += -fpp -fixed -D_MPI
CFLAGS +=  -DFORTRAN_UNDERSCORE -D_MPI
CPLUSPLUSFLAGS +=  -DFORTRAN_UNDERSCORE -D_MPI

MAKEDEP_ARGS = -lc -suffix .mod
AR_ADD = src

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${F95FLAGS} -c -Tf $< -o $@
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
