OPTIM = -O3 -ip -unroll
#OPTIM = -O3
#OPTIM = -O0
#DEBUG = -g -DSEGFAULT_ON_DIE
#DEBUG = -pg
#DEBUG = -Wall
#DEFS =  -DMEM_TRACE

CPLUSPLUS = icc9 -Kc++
CPLUSPLUSOPTS = 

CC = icc9
CCOPTS = 

F77 = ifort9 
F77OPTS = -cpp -f77

LINKER = ifort9 -nofor_main

AROPTS=src

UTILLIB = libutil.a

MATHLIBS = -lmkl_lapack -lmkl_ia32 -lguide -lpthread -lstdc++


