# declarations

F77 = gfortran
F90 = gfortran
F95 = gfortran
CC = gcc
CPLUSPLUS = g++
LINKER = gfortran

#set environment variable GFORTRAN_ERROR_DUMPCORE at runtime to produce cores from runtime errors
DEFAULT_DEBUG = -g -fbounds-check -DDUMP_CORE_ON_ABORT
DEFAULT_OPTIM = -O3

DEFINES += -DFORTRAN_UNDERSCORE  -DGETARG_F2003 -DGFORTRAN
F95FLAGS += -x f95-cpp-input -ffree-line-length-none -ffree-form  -fno-second-underscore -Wunused
F77FLAGS += -x f77-cpp-input -fno-second-underscore
CFLAGS += -fPIC

MAKEDEP_ARGS = -lc -suffix .mod
AR_ADD = src

export DEFAULT_MATH_LINKOPTS = -framework Accelerate

QUIPPY_FCOMPILER = gnu95
QUIPPY_F90FLAGS = -ffree-line-length-none
QUIPPY_DEFINES =  -DGETARG_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE
QUIPPY_CPP = gfortran -E -x f95-cpp-input
QUIPPY_DEBUG = 1

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${F95FLAGS}  -c $< -o $@
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
