# declarations

F77 = ifort
F90 = ifort
F95 = ifort
CC = icc
CPLUSPLUS = icpc -Kc++
LINKER = ifort

DEFAULT_DEBUG = -g -traceback -check bounds -DDUMP_CORE_ON_ABORT 
DEFAULT_OPTIM = -O3 -vec-report0 -unroll -xP -p
CDEBUG = -g -DDUMP_CORE_ON_ABORT
COPTIM = -O3

F95FLAGS += -fpp -free -DGETARG_F2003 
F77FLAGS += -fixed
CFLAGS +=  -DFORTRAN_UNDERSCORE
CPLUSPLUSFLAGS +=  -DFORTRAN_UNDERSCORE 

DEFAULT_MATH_LINKOPTS = -framework Accelerate

MAKEDEP_ARGS = -lc -suffix .mod
AR_ADD = src

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${F95FLAGS} -c -Tf $< -o $@
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
