# declarations

F77 = gfortran -m32
F90 = gfortran -m32
F95 = gfortran -m32
CC = gcc -m32
CPLUSPLUS = g++ -m32
LINKER = gfortran -m32
#LINKER = gfortran -m32 -static-libgfortran -static-libgcc

DEFAULT_DEBUG = -O0 -g -DDUMP_CORE_ON_ABORT -DDEBUG -fbounds-check
DEFAULT_OPTIM = -O3

DEFINES += -DGETARG_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE
F95FLAGS += -x f95-cpp-input -ffree-line-length-none -ffree-form  -fno-second-underscore -Wunused
F77FLAGS += -x f77-cpp-input -fno-second-underscore
CFLAGS +=  -fPIC 

MAKEDEP_ARGS = -lc -suffix .mod
AR_ADD = src

ATOMEYE_LIBS = -L/usr/lib  -Wl,-Bstatic -lm \
   -lutil  -Wl,-Bdynamic -lXpm -lXext -lX11 -ljpeg -lpthread   \
    -Wl,-Bstatic -lreadline -lpng  -lncurses -lz -L/home/jk2/Code/netcdf-32/lib -lnetcdf   -L/home/jk2/Code/hdf5-32/lib -lhdf5_hl -lhdf5 \
   -L/home/jk2/Code/atlas-32/lib -llapack -lf77blas -lcblas -latlas -Wl,-Bdynamic

QUIPPY_FCOMPILER = gnu95
QUIPPY_F90FLAGS = -ffree-line-length-none
QUIPPY_CFLAGS =
QUIPPY_CPP = gfortran -E -x f95-cpp-input
QUIPPY_HAVE_ATOMEYE = 1

export DEFAULT_MATH_LINKOPTS = -llapack -lf77blas -lcblas -latlas

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${F95FLAGS}  -c $< -o $@
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
