OPTIM = -O3 -ip -unroll
#OPTIM = -O3
#OPTIM = -O0
#DEBUG = -g -DSEGFAULT_ON_DIE
#DEBUG = -pg
#DEBUG = -Wall
#DEFS =  -DMEM_TRACE

CPLUSPLUS = icpce9
CPLUSPLUSOPTS = -openmp -openmp-report2

CC = icce9
CCOPTS = 

F77 = iforte9 
F77OPTS = -cpp -f77

LINKER = iforte9 -nofor_main
LINKOPTS = -L/usr/local/shared/intel/mkl72/lib/em64t/

AROPTS=src

UTILLIB = libutil-icc.a

MATHLIBS = -lmkl_lapack64 -lmkl_em64t -lstdc++
