OPTIM = -O3 -ip  -unroll 
#OPTIM = 
#OPTIM =  -O0
#DEBUG = -pg -g -Wall
#DEBUG = -pg -Wall
#DEBUG = -Wall
#DEFS =  -DMEM_TRACE -DUTIL_MPI
DEFS =   -DUTIL_MPI

CPLUSPLUS = mpiCC -Kc++

CC = mpicc

F77 = mpif77
F77OPTS =  -cpp

LINKER = ${F77}

AROPTS=src


UTILLIB = libutil.a






