OPTIM = -O3
#OPTIM = -O0
#DEBUG =  -g
#DEBUG = -pg
#DEBUG = -Wall
#DEFS =  -DMEM_TRACE


CPLUSPLUS = g++
CC = gcc
F77 = g95
F90 = g95
F95 = g95

ARCH_F77FLAGS= -cpp -fno-second-underscore -ffree-line-length-huge ${OPTIM} ${DEBUG}
ARCH_F90FLAGS= -cpp -fno-second-underscore -ffree-line-length-huge ${OPTIM} ${DEBUG}
ARCH_F95FLAGS= -cpp -fno-second-underscore -ffree-line-length-huge ${OPTIM} ${DEBUG}

LINKER = ${F77}

AR_ADD = src

