OPTIM = -O3 -ip -unroll
#OPTIM = -O0
#DEBUG = -pg

DEFS= -DUTIL_MPI 

CPLUSPLUS = icc -Kc++ 
CPLUSPLUSOPTS =  ${INCLUDES}

CC = icc 
COPTS = 

F77 = ifc -Vaxlib
F77OPTS = -i4 -r8

LINKER = ${F77} ${F77OPTS}

AROPTS = src

UTILLIB = libutil-mpi.a

MATHLIBS =   -lmkl_lapack -lmkl_p4 -lguide -lpthread  -lmpi



