# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# H0 X
# H0 X   libAtoms+QUIP: atomistic simulation library
# H0 X
# H0 X   Portions of this code were written by
# H0 X     Albert Bartok-Partay, Silvia Cereda, Gabor Csanyi, James Kermode,
# H0 X     Ivan Solt, Wojciech Szlachta, Csilla Varnai, Steven Winfield.
# H0 X
# H0 X   Copyright 2006-2010.
# H0 X
# H0 X   These portions of the source code are released under the GNU General
# H0 X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# H0 X
# H0 X   If you would like to license the source code under different terms,
# H0 X   please contact Gabor Csanyi, gabor@csanyi.net
# H0 X
# H0 X   Portions of this code were written by Noam Bernstein as part of
# H0 X   his employment for the U.S. Government, and are not subject
# H0 X   to copyright in the USA.
# H0 X
# H0 X
# H0 X   When using this software, please cite the following reference:
# H0 X
# H0 X   http://www.libatoms.org
# H0 X
# H0 X  Additional contributions by
# H0 X    Alessio Comisso, Chiara Gattinoni, and Gianpietro Moras
# H0 X
# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# declarations

F77 = ifort
F90 = ifort
F95 = ifort
CC = icc
CPLUSPLUS = icpc -Kc++
FPP = ifort -E
LINKER = ifort

SAMPLE_DEBUG = -g -traceback -check bounds -DDUMP_CORE_ON_ABORT 
DEBUG = -g -traceback -DDUMP_CORE_ON_ABORT 
OPTIM = -O3 -vec-report0 -unroll -xP
CDEBUG = -g -DDUMP_CORE_ON_ABORT
COPTIM = -O3

DEFINES += -DGETARG_F2003 -DNO_F2003_NEW_LINE -DFORTRAN_UNDERSCORE
F95FLAGS += -fpp -free -warn unused  -fPIC
F77FLAGS += -fpp -fixed -fPIC
CFLAGS += -fPIC 
CPLUSPLUSFLAGS += -fPIC

AR_ADD = src

# rules

QUIPPY_FCOMPILER = intelem
QUIPPY_DEFINES = -DGETARG_F2003
QUIPPY_F90FLAGS = -fpp -free
QUIPPY_F77FLAGS = -fpp -fixed
QUIPPY_CPP = ifort -EP

F95_PRE_FILENAME_FLAG = -Tf
