OPTIM = -O2  -fast  -Minline=levels:10 --no_exceptions
#OPTIM = 
#OPTIM =  -O0

#DEBUG = -pg -g -Wall
#DEBUG = -pg -Wall
#DEBUG = -Wall

#DEFS =   -DMEM_TRACE -DUTIL_MPI
DEFS =   -DUTIL_MPI 

CPLUSPLUS = pgCC
CPLUSPLUSOPTS = -I/opt/scali/include 

CC = pgcc

F77 = pgf90 
F77OPTS = -r8 -cpp

LINKER = ${F77}

AROPTS=src

UTILLIB=libutil-mpi.a



