# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# H0 X
# H0 X   libAtoms+QUIP: atomistic simulation library
# H0 X
# H0 X   Portions of this code were written by
# H0 X     Albert Bartok-Partay, Silvia Cereda, Gabor Csanyi, James Kermode,
# H0 X     Ivan Solt, Wojciech Szlachta, Csilla Varnai, Steven Winfield.
# H0 X
# H0 X   Copyright 2006-2010.
# H0 X
# H0 X   These portions of the source code are released under the GNU General
# H0 X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# H0 X
# H0 X   If you would like to license the source code under different terms,
# H0 X   please contact Gabor Csanyi, gabor@csanyi.net
# H0 X
# H0 X   Portions of this code were written by Noam Bernstein as part of
# H0 X   his employment for the U.S. Government, and are not subject
# H0 X   to copyright in the USA.
# H0 X
# H0 X
# H0 X   When using this software, please cite the following reference:
# H0 X
# H0 X   http://www.libatoms.org
# H0 X
# H0 X  Additional contributions by
# H0 X    Alessio Comisso, Chiara Gattinoni, and Gianpietro Moras
# H0 X
# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# declarations

F77 = gfortran
F90 = gfortran
F95 = gfortran
CC = gcc
CPLUSPLUS = g++
LINKER = gfortran -fopenmp -L/usr/local/lib64 -Wl,-rpath,/usr/local/lib64

SAMPLE_DEBUG = -O0 -g -DDUMP_CORE_ON_ABORT -DDEBUG -fbounds-check
DEBUG = -g -DDUMP_CORE_ON_ABORT
OPTIM = -O3

DEFINES += -DGETARG_F2003 -DGETENV_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE -D_OPENMP
F95FLAGS += -x f95-cpp-input -ffree-line-length-none -ffree-form  -fno-second-underscore -Wunused -fopenmp
F77FLAGS += -x f77-cpp-input -fno-second-underscore -fopenmp
CFLAGS +=  -fPIC -fopenmp

MAKEDEP_ARGS = -lc -suffix .mod
AR_ADD = src

ATOMEYE_LIBS = -L/usr/lib -Wl,-Bstatic  -lm \
   -lutil -Wl,-Bdynamic -lXpm -lXext -lX11 -ljpeg -lpthread  -Wl,-Bstatic   \
   -lreadline -lpng  -lncurses -lz -lnetcdf  -lhdf5_hl -lhdf5  \
   -llapack -lf77blas -lcblas -latlas -Wl,-Bdynamic

QUIPPY_FCOMPILER = gnu95
QUIPPY_F90FLAGS = -ffree-line-length-none -fopenmp
QUIPPY_CFLAGS = -fopenmp
QUIPPY_CPP = gfortran -E -x f95-cpp-input
QUIPPY_INSTALL_OPTS = --home=${HOME}

export DEFAULT_MATH_LINKOPTS = -llapack -lf77blas -lcblas -latlas

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${F95FLAGS}  -c $< -o $@
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
