# declarations

F77 = gfortran
F90 = gfortran
F95 = gfortran
CC = gcc
CPLUSPLUS = g++
#LINKER = gfortran -L/usr/local/lib64 -Wl,-rpath,/usr/local/lib64
LINKER = gfortran -static-libgfortran -static-libgcc

DEFAULT_DEBUG = -O0 -g -DDUMP_CORE_ON_ABORT -DDEBUG -fbounds-check
DEFAULT_OPTIM = -O3

DEFINES += -DGETARG_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE
F95FLAGS += -x f95-cpp-input -ffree-line-length-none -ffree-form  -fno-second-underscore -Wunused
F77FLAGS += -x f77-cpp-input -fno-second-underscore
CFLAGS +=  -fPIC 

MAKEDEP_ARGS = -lc -suffix .mod
AR_ADD = src

QUIPPY_FCOMPILER = gnu95
QUIPPY_F90FLAGS = -ffree-line-length-none
QUIPPY_CFLAGS =
QUIPPY_CPP = gfortran -E -x f95-cpp-input

export DEFAULT_MATH_LINKOPTS = -llapack -lf77blas -lcblas -latlas

# rules

.f95.o:
	@if ( which ${SCRIPT_PATH}protect_mod >/dev/null 2>&1 ); then ${SCRIPT_PATH}protect_mod $(MAKEDEP_ARGS) -- $<; fi
	${F95} ${F95FLAGS}  -c $< -o $@
	@if ( which ${SCRIPT_PATH}unprotect_mod >/dev/null 2>&1 ); then env OD_SKIP=52 ${SCRIPT_PATH}unprotect_mod $(MAKEDEP_ARGS) -- $<; fi
