
OBJS = vacancy_map_mod.o

PROGRAMS = NRL_TB_to_xml DFTB_to_xml eval md lj_example md_example \
  calc_n_poles \
  analyze_md_phonons \
  xyz_to_SPECSYM_start xyz_to_SPECSYM_forces \
  local_E_fd wrap align test

# things that no longer compile
# hybrid_example rotate vacancy_map create_hybrid_cluster vacancy_map_hybrid_generate vacancy_map_hybrid_relax vacancy_map_forcemix_relax mark_hybrid 


