#!/bin/bash

# Perform some simple tests on code style on all files specified on command line

sources="$@"
failed=0


# Check for "end function" and "end subroutine" without function name
for func in function subroutine; do
    if (egrep -q "^\W*end $func\W*$" $sources); then
	echo
	echo Found some \"end $func\" lines without names:
	
	egrep -n "^\W*end $func\W*$" $sources | awk -F ':' '{print $1 " line " $2}'

    failed=1
    fi
done

# Exit with error code 1 if any check failed
if (( $failed==1 )); then
    echo
    echo Some code style checks have failed!
    exit 1
fi


# All checks out okay
exit 0