#!/usr/bin/perl -w
use strict;

while (my $line = <STDIN>) {
   my $in_quote = 0;
   my $start_quote;
   my $line_start = 0;
   my $out_line = "";
   my $no_wrap=0;
   for (my $i=0; $i <= length($line); $i++) {
      my $c = substr($line, $i, 1);
      if ($in_quote) {
	 $out_line .= "$c";
	 if ($c eq $start_quote) {
	    $in_quote=0;
	 }
      } else { # not in quote
	 if ($c eq '!') {
	    # $out_line .= substr($line, $i, length($line)-$i);
	    # $no_wrap = 1;
	    print_wrapped_line("$out_line\n");
	    $out_line ="";
	    last;
	 } elsif ($c eq '"' || $c eq "'") {
	    $in_quote = 1;
	    $start_quote=$c;
	    $out_line .= $c;
	 } elsif ($c eq ';') {
	    print_wrapped_line ("$out_line\n");
	    $out_line ="";
	    $line_start = $i + 1;
	 } else {
	    $out_line .= $c;
	 }
      }
   }
   if ($no_wrap) {
      print $out_line;
   } else {
      print_wrapped_line($out_line);
   }
}


sub print_wrapped_line {
   my $out_line = $_[0];
   my $in_quote = 0;
   my $start_quote;

   if (length($out_line) <= 130) {
      print "$out_line";
   } else { # length > 130
      my $i;
      for ($i=length($out_line); $i >= 129; $i--) {
	 my $c = substr($out_line, $i, 1);
	 if ($in_quote) {
	    if ($c eq $start_quote) {
	       $start_quote="";
	       $in_quote = 0;
	    }
	 } else {
	    if ($c eq "'" || $c eq '"') {
	       $start_quote = $c;
	       $in_quote = 1;
	    }
	 }
      }
      if ($in_quote) {
	 my $remaining_line = substr($out_line,129,length($out_line)-128);
	 print substr($out_line,0,129)."$start_quote // &\n";
	 print "$start_quote";
	 print_wrapped_line($remaining_line);
      } else {
	 for ($i=128; $i >= 0; $i--) {
	    my $c = substr($out_line, $i, 1);
	    if ($in_quote) {
	       if ($c eq $start_quote) {
		  $start_quote="";
		  $in_quote = 0;
	       }
	    } else {
	       if ($c eq "'" || $c eq '"') {
		  $start_quote = $c;
		  $in_quote = 1;
	       }
	    }
	    if (! $in_quote) {
	       if ($c =~ /[\s),]/) {
		  my $remaining_line = substr($out_line,$i+1,length($out_line)-$i);
		  if ($remaining_line =~ /^\s*&?\s*$/m) {
		     print $out_line;
		  } else {
		     print substr($out_line,0,$i+1)." &\n";
		     print_wrapped_line($remaining_line);
		  }
		  last;
	       } elsif ($c =~ /['"]/) {
		  my $remaining_line = substr($out_line,$i,length($out_line)-$i+1);
		  if ($remaining_line =~ /^\s*$/m) {
		     print $out_line;
		  } else {
		     print substr($out_line,0,$i)." &\n";
		     print_wrapped_line($remaining_line);
		  }
		  last;
	       } elsif ($c =~ /['"]/) {
	       }
	    }
	 }
      }
      if ($i <= 0) {
	 die("Failed to print wrapped line:\n$out_line\n");
      }
   }
}

exit 0;
