#!/bin/bash
# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# H0 X
# H0 X   libAtoms+QUIP: atomistic simulation library
# H0 X
# H0 X   Portions of this code were written by
# H0 X     Albert Bartok-Partay, Silvia Cereda, Gabor Csanyi, James Kermode,
# H0 X     Ivan Solt, Wojciech Szlachta, Csilla Varnai, Steven Winfield.
# H0 X
# H0 X   Copyright 2006-2010.
# H0 X
# H0 X   These portions of the source code are released under the GNU General
# H0 X   Public License, version 2, http://www.gnu.org/copyleft/gpl.html
# H0 X
# H0 X   If you would like to license the source code under different terms,
# H0 X   please contact Gabor Csanyi, gabor@csanyi.net
# H0 X
# H0 X   Portions of this code were written by Noam Bernstein as part of
# H0 X   his employment for the U.S. Government, and are not subject
# H0 X   to copyright in the USA.
# H0 X
# H0 X
# H0 X   When using this software, please cite the following reference:
# H0 X
# H0 X   http://www.libatoms.org
# H0 X
# H0 X  Additional contributions by
# H0 X    Alessio Comisso, Chiara Gattinoni, and Gianpietro Moras
# H0 X
# H0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# Remove old documentation
rm -rf doctmp
mkdir doctmp
cd doctmp

# Make a copy of all input source files with function and subroutine
# names at the end of each subprogram, so that f90doc doesn't get
# confused

for base in libAtoms QUIP_Core QUIP_Utils; do
    rm *.f95
    [[ -f ../$base/intro.tex ]] && cp ../$base/intro.tex ${base}_intro.tex
    for f in ../$base/*.f95; do
	if ! echo $f | grep -q header; then 
	    echo $f
	    perl -e '
while(<>) {
    if (/^(double precision\s+)?\s*(recursive\s+)?(subroutine|function)\s+(\w*)/) {
	$last_subrt = $4;
	print $_;
    }
    elsif (/^\s*end\s+(subroutine|function)\s*$/) {
	chomp($_);
	print $_." ".$last_subrt."\n";
    }
    else { print $_; }
}' $f > `basename $f`
	fi
    done

    ../Tools/quippy/f90doc.py -n -l -p *.f95 > $base.tex
done

cat > quip-reference-manual.tex <<EOF
\documentclass[11pt,twoside]{book}
\textheight 9.5in
\topmargin -0.5in
\textwidth 6in
\oddsidemargin 0in
\evensidemargin 0in
%\parindent=0.3in
\pagestyle{headings}

%Set depth of contents page
\setcounter{tocdepth}{2}

\usepackage {makeidx, fancyhdr, boxedminipage, multind, colortbl, sverb}
\usepackage[dvips]{graphicx}
\pagestyle{fancy}

%\renewcommand{\sectionmark}[1]{\markboth{\thesection.\ #1}}
\renewcommand{\sectionmark}[1]{\markboth{}{#1}}
\fancyhf{}
\fancyhead[RE,LO]{\bfseries{\thepage}}
\fancyhead[RO,LE]{\bfseries{\rightmark}}
\renewcommand{\headrulewidth}{0.5pt}

\makeindex{general}

\begin{document}


\title{QUIP Reference Manual}
\date{\today}
\author{James Kermode, Noam Bernstein, Silvia Cereda and G\'abor Cs\'anyi}
\maketitle

\thispagestyle{empty}

\tableofcontents

% Defines paragraphs
\setlength{\parskip}{5mm}
\setlength{\parindent}{0em}
EOF


for base in libAtoms QUIP_Core QUIP_Utils; do
    escbase=$(echo $base | sed -e 's/_/\\_/')
    echo "\chapter{$escbase}" >> quip-reference-manual.tex
    [[ -f ${base}_intro.tex ]] && echo "\input{${base}_intro.tex}" >> quip-reference-manual.tex
    echo "\input{$base.tex}" >> quip-reference-manual.tex
done

cat >> quip-reference-manual.tex <<EOF
\printindex{general}{Index}

\end{document}
EOF

# LaTeX it
latex quip-reference-manual.tex
latex quip-reference-manual.tex
makeindex general
latex quip-reference-manual.tex

# Make postscript
dvips quip-reference-manual.dvi -o quip-reference-manual.ps

# And PDF
dvipdfm quip-reference-manual.dvi

# Uncomment this line if you have latex2html and want HTML docs
#latex2html $base.tex

# Copy output files out of 'doctmp'
cp quip-reference-manual.pdf ..

# Tidy up
cd .. && rm -rf doctmp
