#!/bin/bash

# Remove old documentation
rm -rf doctmp
mkdir doctmp
cd doctmp

# Make a copy of all input source files with function and subroutine
# names at the end of each subprogram, so that f90doc doesn't get
# confused

for base in libAtoms QUIP_Core QUIP_Utils; do
    rm *.f95
    [[ -f ../$base/intro.tex ]] && cp ../$base/intro.tex ${base}_intro.tex
    for f in ../$base/*.f95; do
	if ! echo $f | grep -q header; then 
	    echo $f
	    perl -e '
while(<>) {
    if (/^(double precision\s+)?\s*(recursive\s+)?(subroutine|function)\s+(\w*)/) {
	$last_subrt = $4;
	print $_;
    }
    elsif (/^\s*end\s+(subroutine|function)\s*$/) {
	chomp($_);
	print $_." ".$last_subrt."\n";
    }
    else { print $_; }
}' $f > `basename $f`
	fi
    done

    ../Tools/f90doc.py -n -l -p *.f95 > $base.tex
done

cat > quip-reference-manual.tex <<EOF
\documentclass[11pt,twoside]{book}
\textheight 9.5in
\topmargin -0.5in
\textwidth 6in
\oddsidemargin 0in
\evensidemargin 0in
%\parindent=0.3in
\pagestyle{headings}

%Set depth of contents page
\setcounter{tocdepth}{2}

\usepackage {makeidx, fancyhdr, boxedminipage, multind, colortbl, sverb}
\usepackage[dvips]{graphicx}
\pagestyle{fancy}

%\renewcommand{\sectionmark}[1]{\markboth{\thesection.\ #1}}
\renewcommand{\sectionmark}[1]{\markboth{}{#1}}
\fancyhf{}
\fancyhead[RE,LO]{\bfseries{\thepage}}
\fancyhead[RO,LE]{\bfseries{\rightmark}}
\renewcommand{\headrulewidth}{0.5pt}

\makeindex{general}

\begin{document}


\title{QUIP Reference Manual}
\date{\today}
\author{James Kermode, Noam Bernstein, Silvia Cereda and G\'abor Cs\'anyi}
\maketitle

\thispagestyle{empty}

\tableofcontents

% Defines paragraphs
\setlength{\parskip}{5mm}
\setlength{\parindent}{0em}
EOF


for base in libAtoms QUIP_Core QUIP_Utils; do
    escbase=$(echo $base | sed -e 's/_/\\_/')
    echo "\chapter{$escbase}" >> quip-reference-manual.tex
    [[ -f ${base}_intro.tex ]] && echo "\input{${base}_intro.tex}" >> quip-reference-manual.tex
    echo "\input{$base.tex}" >> quip-reference-manual.tex
done

cat >> quip-reference-manual.tex <<EOF
\printindex{general}{Index}

\end{document}
EOF

# LaTeX it
latex quip-reference-manual.tex
latex quip-reference-manual.tex
makeindex general
latex quip-reference-manual.tex

# Make postscript
dvips quip-reference-manual.dvi -o quip-reference-manual.ps

# And PDF
dvipdfm quip-reference-manual.dvi

# Uncomment this line if you have latex2html and want HTML docs
#latex2html $base.tex

# Copy output files out of 'doctmp'
cp quip-reference-manual.pdf ..

# Tidy up
cd .. && rm -rf doctmp